#include<iostream>
#include<fstream>
#include<vector>
#include<string>

using namespace std;

class CircuitProtection
{
private:

    string circuitName;
    double supplyVoltage;
    double totalPower;
    double loadCurrent;
    double designCurrent;
    double recommendedRating;
    string status;

public:

    void inputDetails();
    bool validateInput();

    void calculateLoadCurrent();
    void calculateDesignCurrent();

    void recommendRating();

    void displayReport();

    void saveReport(ofstream &file);
};

void CircuitProtection::inputDetails()
{
    cin.ignore();

    cout << "\nEnter Circuit Name: ";
    getline(cin, circuitName);

    cout << "Enter Supply Voltage (V): ";
    cin >> supplyVoltage;

    cout << "Enter Total Load Power (W): ";
    cin >> totalPower;
}

bool CircuitProtection::validateInput()
{
    if(supplyVoltage <= 0)
    {
        cout << "\nERROR : Voltage must be greater than zero.\n";
        return false;
    }

    if(totalPower <= 0)
    {
        cout << "\nERROR : Power must be greater than zero.\n";
        return false;
    }

    return true;
}

void CircuitProtection::calculateLoadCurrent()
{
    loadCurrent = totalPower / supplyVoltage;
}

void CircuitProtection::calculateDesignCurrent()
{
    designCurrent = loadCurrent * 1.25;
}

void CircuitProtection::recommendRating()
{
    vector<int> ratings;

    ratings.push_back(6);
    ratings.push_back(10);
    ratings.push_back(16);
    ratings.push_back(20);
    ratings.push_back(25);
    ratings.push_back(32);
    ratings.push_back(40);
    ratings.push_back(63);

    recommendedRating = 0;

    for(unsigned int i=0; i<ratings.size(); i++)
    {
        if(designCurrent <= ratings[i])
        {
            recommendedRating = ratings[i];
            status = "Suitable standard rating found.";
            return;
        }
    }
   status = "WARNING: Design current exceeds 63A.";
}void CircuitProtection::displayReport()

{
    cout << fixed;
    cout << "\n";
    cout << "          PROTECTION REPORT\n";

    cout << "Circuit Name              : " << circuitName << endl;
    cout << "Supply Voltage (V)        : " << supplyVoltage << endl;
    cout << "Total Load Power (W)      : " << totalPower << endl;
    cout << "Load Current (A)          : " << loadCurrent << endl;
    cout << "Design Current (A)        : " << designCurrent << endl;

    if(recommendedRating != 0)
        cout << "Recommended Rating (A)    : "
             << recommendedRating << endl;
    else
        cout << "Recommended Rating        : NONE" << endl;

    cout << "Protection Status         : "
         << status << endl;
}

void CircuitProtection::saveReport(ofstream &file)
{
    file << fixed;

    file << "_________________________________________________\n";
    file << "Circuit Name          : " << circuitName << endl;
    file << "Supply Voltage (V)    : " << supplyVoltage << endl;
    file << "Total Power (W)       : " << totalPower << endl;
    file << "Load Current (A)      : " << loadCurrent << endl;
    file << "Design Current (A)    : " << designCurrent << endl;

    if(recommendedRating != 0)
        file << "Recommended Rating    : "
             << recommendedRating << " A\n";
    else
        file << "Recommended Rating    : NONE\n";

    file << "Status                : "
         << status << endl;

    file << "__________________________________________________\n\n";
}

int main()
{
    int numberOfCircuits;

    cout << "      CIRCUIT BREAKER AND FUSE SELECTION SYSTEM"<<endl;
    cout << "_________________________________________________________\n";

    cout << "\nEnter Number of Circuits to Assess: ";
    cin >> numberOfCircuits;

    while(numberOfCircuits <= 0)
    {
        cout << "\nInvalid Number!\n";
        cout << "Enter Again: ";
        cin >> numberOfCircuits;
    }

    ofstream report("protection_report.txt");

    if(!report)
    {
        cout << "\nUnable to create report file.\n";
        return 0;
    }

    report << "CIRCUIT BREAKER AND FUSE SELECTION REPORT\n";
    report << "Generated by BEE208 Project\n\n";

    for(int i=1; i<=numberOfCircuits; i++)
    {
        cout << "\n";
        cout << "             CIRCUIT " << i << endl;
        cout << "_________________________________________________\n";

        CircuitProtection circuit;

        do
        {
            circuit.inputDetails();

        }while(!circuit.validateInput());

        circuit.calculateLoadCurrent();

        circuit.calculateDesignCurrent();

        circuit.recommendRating();

        circuit.displayReport();

        circuit.saveReport(report);
    }

    report.close();

    cout << "\n";
    cout << "Protection report saved successfully.\n";
    cout << "Filename: protection_report.txt\n";
    cout << "____________________________________________________________=\n";

    cout << "\nThank you for using this application.\n";

    return 0;
}
